version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: card_user
      POSTGRES_PASSWORD: card_user_password
      POSTGRES_DB: credit_statements
    ports:
      - '5445:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis-session
    command: redis-server --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis-data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - app_network

volumes:
  postgres_data:
  redis-data:
    driver: local

networks:
  app_network:
    driver: bridge
